language: generic

dist: xenial

os: linux

services:
  - docker

before_install:
  - docker build -t 2yonghyun/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true 2yonghyun/react-test-app npm run test

after_success:
  - docker build -t 2yonghyun/docker-frontend ./frontend
  - docker build -t 2yonghyun/docker-backend ./backend
  - docker build -t 2yonghyun/docker-nginx ./nginx

  - echo "$DOCKER_HUB_ACCESSKEY" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push 2yonghyun/docker-frontend
  - docker push 2yonghyun/docker-backend
  - docker push 2yonghyun/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-1-403462778751
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESSKEY
  secret_access_key: $AWS_SECRET_ACCESSKEY